#ifdef __cplusplus
extern "C" {
#endif
/*
ANSI C code generated by SmartEiffel The GNU Eiffel Compiler, Eiffel tools and libraries
Release 2.3 (Thursday July 11th 2007) [Antoine-Auguste Parmentier]
Copyright (C), 1994-2002 - INRIA - LORIA - ESIAL UHP Nancy 1 - FRANCE
Copyright (C), 2003-2005 - INRIA - LORIA - IUT Charlemagne Nancy 2 - FRANCE
D.COLNET, P.RIBET, C.ADRIAN, V.CROIZIER F.MERIZEN - SmartEiffel@loria.fr
http://SmartEiffel.loria.fr
C Compiler options used: -pipe
*/

#ifdef __cplusplus
}
#endif
#include "mediatheque.h"
#ifdef __cplusplus
extern "C" {
#endif

T0*se_ms(int c,char*e){
/* Allocate a Manifest STRING.*/
T7*s=new7();
s->_count=c;
s->_capacity=c+1;
s->_storage=((T9)new9(c+1));
memcpy(s->_storage,e,c+1);
return((T0*)s);}/*--*/

T0*se_string(char*e){
/* Allocate an Eiffel STRING by copying C char*e */
int c=strlen(e);
T7*s=new7();
s->_count=c;
s->_capacity=c+1;
s->_storage=((T9)new9(c+1));
memcpy(s->_storage,e,c+1);
return((T0*)s);}/*--*/

void manifest_string_mark1(void){
}/*--*/

void once_function_mark(void){
/*NON_VOID_NO_DISPATCH:*/
/*Ordinary once functions:*/
if(NULL!=oBC13io)gc_mark40((T40*)(oBC13io));
if(NULL!=oBC44last_string)gc_mark7((T7*)(oBC44last_string));
if(NULL!=oBC13std_output)gc_mark47((T47*)(oBC13std_output));
if(NULL!=oBC13std_input)gc_mark48((T48*)(oBC13std_input));
}/*--*/

void gc_start(void){
if(gc_is_off)return;
if(garbage_delayed())return;
handle(SE_HANDLE_ENTER_GC,NULL);
gcmt_tail_addr=(((char*)(gcmt[gcmt_used-1]))+(gcmt[gcmt_used-1])->size);
((gc25*)eiffel_root_object)->header.flag=FSOH_UNMARKED;
gc_free48=(void*)0;
gc_free47=(void*)0;
gc_free40=(void*)0;
gc_free49=(void*)0;
gc_free25=(void*)0;
if(na_env9.store_left>0){
na_env9.store->header.size=na_env9.store_left;
na_env9.store->header.magic_flag=RSOH_FREE;
na_env9.store_left=0;
}
na_env9.chunk_list=NULL;
na_env9.store_chunk=NULL;
gc_free7=(void*)0;
gc_mark25(eiffel_root_object);
manifest_string_mark1();
once_function_mark();
{int i=SE_MAXID-1;
while(i>=0){
if(g[i]!=NULL)gc_mark7(g[i]);
i--;}
}
{int i=SE_MAXID-1;
while(i>=0){
if(t[i]!=NULL)gc_mark7(t[i]);
i--;}
}
mark_stack_and_registers();
gc_sweep();
collector_counter++;
handle(SE_HANDLE_EXIT_GC,NULL);
}/*--*/
gc48*store48=(void*)0;
int store_left48=0;
fsoc*store_chunk48=(void*)0;
gc48*gc_free48=(void*)0;
gc47*store47=(void*)0;
int store_left47=0;
fsoc*store_chunk47=(void*)0;
gc47*gc_free47=(void*)0;
gc40*store40=(void*)0;
int store_left40=0;
fsoc*store_chunk40=(void*)0;
gc40*gc_free40=(void*)0;
gc49*store49=(void*)0;
int store_left49=0;
fsoc*store_chunk49=(void*)0;
gc49*gc_free49=(void*)0;
gc25*store25=(void*)0;
int store_left25=0;
fsoc*store_chunk25=(void*)0;
gc25*gc_free25=(void*)0;
na_env na_env9={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark9};
gc7*store7=(void*)0;
int store_left7=0;
fsoc*store_chunk7=(void*)0;
gc7*gc_free7=(void*)0;

void gc_sweep48(fsoc*c){
gc48*o1,*o2;
o1=((gc48*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store48;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free48;
gc_free48=o1;
}
}
}
else{
int dead=1;
gc48* old_gc_free = gc_free48;
o2=o1+c->count_minus_one;
for(;o1<=o2;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
dead=0;}
else{
o1->header.next=gc_free48;
gc_free48=o1;
}
}
if (dead){
gc_free48 = old_gc_free;
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
}
}/*--*/

void gc_mark48(T48*o){
se_gc_check_id(o,48);
{
if(((gc48*)o)->header.flag==FSOH_UNMARKED){
((gc48*)o)->header.flag=FSOH_MARKED;
/*i2p*/if(NULL!=o->_buffer)gc_mark9((o->_buffer));
}
}
}/*--*/

void gc_align_mark48(fsoc*c,gc48*p){
gc48*b=((gc48*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store48)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T48*o=(&(p->object));
((gc48*)o)->header.flag=FSOH_MARKED;
/*i2p*/if(NULL!=o->_buffer)gc_mark9((o->_buffer));
}
}
}/*--*/
fsoc H48={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark48,
(void(*)(mch*))gc_sweep48},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc48))-1)};

T48*new48(void){
gc48*n;
fsoc*c;
if(store_left48>1){
store_left48--;
n=store48++;
}
else if(gc_free48!=NULL){
n=gc_free48;
gc_free48=n->header.next;
}
else if(store_left48==1){
store_left48=0;
store_chunk48->header.state_type=FSO_USED_CHUNK;
n=store48++;
}
else{
c=gc_fsoc_get1();
if(gc_free48!=NULL){
n=gc_free48;
gc_free48=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk48=c;
*store_chunk48=H48;
store48=((gc48*)(&(store_chunk48->first_object)));
store_left48=H48.count_minus_one;
n=store48++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M48;
return((T48*)n);
}/*--*/

void gc_sweep47(fsoc*c){
gc47*o1,*o2;
o1=((gc47*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store47;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free47;
gc_free47=o1;
}
}
}
else{
int dead=1;
gc47* old_gc_free = gc_free47;
o2=o1+c->count_minus_one;
for(;o1<=o2;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
dead=0;}
else{
o1->header.next=gc_free47;
gc_free47=o1;
}
}
if (dead){
gc_free47 = old_gc_free;
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
}
}/*--*/

void gc_mark47(T47*o){
se_gc_check_id(o,47);
{
if(((gc47*)o)->header.flag==FSOH_UNMARKED){
((gc47*)o)->header.flag=FSOH_MARKED;
/*i4p*/if(NULL!=o->_buffer)gc_mark9((o->_buffer));
/*i4p*/}
}
}/*--*/

void gc_align_mark47(fsoc*c,gc47*p){
gc47*b=((gc47*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store47)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T47*o=(&(p->object));
((gc47*)o)->header.flag=FSOH_MARKED;
/*i4p*/if(NULL!=o->_buffer)gc_mark9((o->_buffer));
/*i4p*/}
}
}/*--*/
fsoc H47={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark47,
(void(*)(mch*))gc_sweep47},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc47))-1)};

T47*new47(void){
gc47*n;
fsoc*c;
if(store_left47>1){
store_left47--;
n=store47++;
}
else if(gc_free47!=NULL){
n=gc_free47;
gc_free47=n->header.next;
}
else if(store_left47==1){
store_left47=0;
store_chunk47->header.state_type=FSO_USED_CHUNK;
n=store47++;
}
else{
c=gc_fsoc_get1();
if(gc_free47!=NULL){
n=gc_free47;
gc_free47=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk47=c;
*store_chunk47=H47;
store47=((gc47*)(&(store_chunk47->first_object)));
store_left47=H47.count_minus_one;
n=store47++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M47;
return((T47*)n);
}/*--*/

void gc_sweep40(fsoc*c){
gc40*o1,*o2;
o1=((gc40*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store40;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free40;
gc_free40=o1;
}
}
}
else{
int dead=1;
gc40* old_gc_free = gc_free40;
o2=o1+c->count_minus_one;
for(;o1<=o2;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
dead=0;}
else{
o1->header.next=gc_free40;
gc_free40=o1;
}
}
if (dead){
gc_free40 = old_gc_free;
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
}
}/*--*/

void gc_mark40(T40*o){
se_gc_check_id(o,40);
{
if(((gc40*)o)->header.flag==FSOH_UNMARKED){
((gc40*)o)->header.flag=FSOH_MARKED;
/*i3p*/}
}
}/*--*/

void gc_align_mark40(fsoc*c,gc40*p){
gc40*b=((gc40*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store40)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T40*o=(&(p->object));
((gc40*)o)->header.flag=FSOH_MARKED;
/*i3p*/}
}
}/*--*/
fsoc H40={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark40,
(void(*)(mch*))gc_sweep40},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc40))-1)};

T40*new40(void){
gc40*n;
fsoc*c;
if(store_left40>1){
store_left40--;
n=store40++;
}
else if(gc_free40!=NULL){
n=gc_free40;
gc_free40=n->header.next;
}
else if(store_left40==1){
store_left40=0;
store_chunk40->header.state_type=FSO_USED_CHUNK;
n=store40++;
}
else{
c=gc_fsoc_get1();
if(gc_free40!=NULL){
n=gc_free40;
gc_free40=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk40=c;
*store_chunk40=H40;
store40=((gc40*)(&(store_chunk40->first_object)));
store_left40=H40.count_minus_one;
n=store40++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M40;
return((T40*)n);
}/*--*/

void gc_sweep49(fsoc*c){
gc49*o1,*o2;
o1=((gc49*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store49;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free49;
gc_free49=o1;
}
}
}
else{
int dead=1;
gc49* old_gc_free = gc_free49;
o2=o1+c->count_minus_one;
for(;o1<=o2;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
dead=0;}
else{
o1->header.next=gc_free49;
gc_free49=o1;
}
}
if (dead){
gc_free49 = old_gc_free;
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
}
}/*--*/

void gc_mark49(T49*o){
se_gc_check_id(o,49);
{
if(((gc49*)o)->header.flag==FSOH_UNMARKED){
((gc49*)o)->header.flag=FSOH_MARKED;
/*i10p*/if(NULL!=o->_buffer)gc_mark9((o->_buffer));
/*i10p*/if(NULL!=o->_path)gc_mark7((T7*)(o->_path));
}
}
}/*--*/

void gc_align_mark49(fsoc*c,gc49*p){
gc49*b=((gc49*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store49)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T49*o=(&(p->object));
((gc49*)o)->header.flag=FSOH_MARKED;
/*i10p*/if(NULL!=o->_buffer)gc_mark9((o->_buffer));
/*i10p*/if(NULL!=o->_path)gc_mark7((T7*)(o->_path));
}
}
}/*--*/
fsoc H49={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark49,
(void(*)(mch*))gc_sweep49},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc49))-1)};

T49*new49(void){
gc49*n;
fsoc*c;
if(store_left49>1){
store_left49--;
n=store49++;
}
else if(gc_free49!=NULL){
n=gc_free49;
gc_free49=n->header.next;
}
else if(store_left49==1){
store_left49=0;
store_chunk49->header.state_type=FSO_USED_CHUNK;
n=store49++;
}
else{
c=gc_fsoc_get1();
if(gc_free49!=NULL){
n=gc_free49;
gc_free49=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk49=c;
*store_chunk49=H49;
store49=((gc49*)(&(store_chunk49->first_object)));
store_left49=H49.count_minus_one;
n=store49++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M49;
return((T49*)n);
}/*--*/

void gc_sweep25(fsoc*c){
gc25*o1,*o2;
o1=((gc25*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store25;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free25;
gc_free25=o1;
}
}
}
else{
int dead=1;
gc25* old_gc_free = gc_free25;
o2=o1+c->count_minus_one;
for(;o1<=o2;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
dead=0;}
else{
o1->header.next=gc_free25;
gc_free25=o1;
}
}
if (dead){
gc_free25 = old_gc_free;
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
}
}/*--*/

void gc_mark25(T25*o){
se_gc_check_id(o,25);
{
((gc25*)o)->header.flag=FSOH_MARKED;
}
}/*--*/

void gc_align_mark25(fsoc*c,gc25*p){
gc25*b=((gc25*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store25)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T25*o=(&(p->object));
((gc25*)o)->header.flag=FSOH_MARKED;
}
}
}/*--*/
fsoc H25={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark25,
(void(*)(mch*))gc_sweep25},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc25))-1)};

T25*new25(void){
gc25*n;
fsoc*c;
if(store_left25>1){
store_left25--;
n=store25++;
}
else if(gc_free25!=NULL){
n=gc_free25;
gc_free25=n->header.next;
}
else if(store_left25==1){
store_left25=0;
store_chunk25->header.state_type=FSO_USED_CHUNK;
n=store25++;
}
else{
c=gc_fsoc_get1();
if(gc_free25!=NULL){
n=gc_free25;
gc_free25=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk25=c;
*store_chunk25=H25;
store25=((gc25*)(&(store_chunk25->first_object)));
store_left25=H25.count_minus_one;
n=store25++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M25;
return((T25*)n);
}/*--*/

void gc_mark9(T9 o){
if(NULL==gc_find_chunk(o))
return; /* external NA */
(((rsoh*)o)-1)->header.magic_flag=RSOH_MARKED;
}/*--*/

T9 new9(unsigned int size){
size=(size*sizeof(T3))+sizeof(rsoh);
size=((size+(sizeof(double)-1))&~(sizeof(double)-1));
if (size<=(na_env9.store_left)){
rsoh*r=na_env9.store;
na_env9.store_left-=size;
if(na_env9.store_left>sizeof(rsoh)){
r->header.size=size;
na_env9.store=((rsoh*)(((char*)(na_env9.store))+size));
}
else {
r->header.size=size+na_env9.store_left;
na_env9.store_left=0;
}
(r->header.magic_flag)=RSOH_UNMARKED;
((void)memset((r+1),0,r->header.size-sizeof(rsoh)));
return((T9)(r+1));
}
return((T9)new_na(&na_env9,size));
}/*--*/

void gc_sweep7(fsoc*c){
gc7*o1,*o2;
o1=((gc7*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store7;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free7;
gc_free7=o1;
}
}
}
else{
int dead=1;
gc7* old_gc_free = gc_free7;
o2=o1+c->count_minus_one;
for(;o1<=o2;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
dead=0;}
else{
o1->header.next=gc_free7;
gc_free7=o1;
}
}
if (dead){
gc_free7 = old_gc_free;
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
}
}/*--*/

void gc_mark7(T7*o){
se_gc_check_id(o,7);
{
if(((gc7*)o)->header.flag==FSOH_UNMARKED){
((gc7*)o)->header.flag=FSOH_MARKED;
/*i3p*/if(NULL!=o->_storage)gc_mark9((o->_storage));
}
}
}/*--*/

void gc_align_mark7(fsoc*c,gc7*p){
gc7*b=((gc7*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store7)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T7*o=(&(p->object));
((gc7*)o)->header.flag=FSOH_MARKED;
/*i3p*/if(NULL!=o->_storage)gc_mark9((o->_storage));
}
}
}/*--*/
fsoc H7={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark7,
(void(*)(mch*))gc_sweep7},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc7))-1)};

T7*new7(void){
gc7*n;
fsoc*c;
if(store_left7>1){
store_left7--;
n=store7++;
}
else if(gc_free7!=NULL){
n=gc_free7;
gc_free7=n->header.next;
}
else if(store_left7==1){
store_left7=0;
store_chunk7->header.state_type=FSO_USED_CHUNK;
n=store7++;
}
else{
c=gc_fsoc_get1();
if(gc_free7!=NULL){
n=gc_free7;
gc_free7=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk7=c;
*store_chunk7=H7;
store7=((gc7*)(&(store_chunk7->first_object)));
store_left7=H7.count_minus_one;
n=store7++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M7;
return((T7*)n);
}/*--*/
T25*eiffel_root_object=(void*)0;
int se_argc;
char**se_argv;
T7*g[122];
T7*t[122];
char*p[122];
void(*se_prinT[122])(FILE*,void*);
int se_strucT[122]={0,sizeof(T1),sizeof(T2),sizeof(T3),0,0,sizeof(T6),sizeof(T7),sizeof(T8),sizeof(T9),sizeof(T10),0,0,0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
sizeof(T25),
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
sizeof(T40),
0,
0,
0,
0,
0,
0,
sizeof(T47),
sizeof(T48),
sizeof(T49),
0,
0,
0,
0,
0,
0,
0,
0,
0,
0};

void se_atexit(void){
se_frame_descriptor fd={"<atexit wrapper>",0,0,"",1};
se_dump_stack ds;
ds.fd=&fd;
ds.p=0;
ds.caller=NULL;
ds.exception_origin=NULL;
ds.locals=NULL;
r47se_atexit(&ds,NULL/*Unused Target*/);
}/*--*/

void initialize_eiffel_runtime(int argc,char*argv[]){
/*[INTERNAL_C_LOCAL list*/
T0* tmp0;
/*INTERNAL_C_LOCAL list]*/
se_frame_descriptor irfd={"<runtime init>",0,0,"",1};
se_dump_stack ds = {NULL,NULL,0,NULL,NULL};
ds.fd=&irfd;
set_dump_stack_top(&ds);/*link*/
se_argc=argc;
se_argv=argv;
atexit(se_atexit);
gcmt=((mch**)se_malloc((gcmt_max+1)*sizeof(void*)));
#ifdef FIXED_STACK_BOTTOM
if (!stack_bottom) stack_bottom=((void**)(void*)(&argc));
#endif
p[0]="???";
p[25]="/comptes/E134887R/Documents/M1_MIAGE/GLO/Mediatheque/mediatheque/mediatheque.e";
p[100]="/usr/local/opt/SmartEiffel/lib/kernel/procedure.e";
p[94]="/usr/local/opt/SmartEiffel/lib/kernel/memory.e";
p[15]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[16]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[65]="/usr/local/opt/SmartEiffel/lib/kernel/routine.e";
p[17]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[18]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[19]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[20]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[21]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[22]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[23]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[14]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[24]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[8]="/usr/local/opt/SmartEiffel/lib/kernel/pointer.e";
p[99]="/usr/local/opt/SmartEiffel/lib/kernel/reference.e";
p[64]="/usr/local/opt/SmartEiffel/lib/kernel/function.e";
p[6]="/usr/local/opt/SmartEiffel/lib/kernel/boolean.e";
p[53]="/usr/local/opt/SmartEiffel/lib/kernel/safe_equal.e";
p[13]="/usr/local/opt/SmartEiffel/lib/kernel/any.e";
p[101]="/usr/local/opt/SmartEiffel/lib/kernel/weak_reference.e";
p[36]="/usr/local/opt/SmartEiffel/lib/kernel/platform.e";
p[73]="/usr/local/opt/SmartEiffel/lib/kernel/internal/internals_handler.e";
p[85]="/usr/local/opt/SmartEiffel/lib/kernel/internal/native_array_internals.e";
p[45]="/usr/local/opt/SmartEiffel/lib/kernel/internal/typed_internals.e";
p[67]="/usr/local/opt/SmartEiffel/lib/kernel/internal/native_array_collector.e";
p[46]="/usr/local/opt/SmartEiffel/lib/kernel/internal/internals.e";
p[63]="/usr/local/opt/SmartEiffel/lib/storage/collection.e";
p[80]="/usr/local/opt/SmartEiffel/lib/storage/collection/fast_array.e";
p[66]="/usr/local/opt/SmartEiffel/lib/storage/collection/array.e";
p[102]="/usr/local/opt/SmartEiffel/lib/storage/collection/ring_array.e";
p[52]="/usr/local/opt/SmartEiffel/lib/storage/low_level/native_array.e";
p[93]="/usr/local/opt/SmartEiffel/lib/storage/low_level/recycling_pool.e";
p[68]="/usr/local/opt/SmartEiffel/lib/storage/internal/arrayed_collection.e";
p[106]="/usr/local/opt/SmartEiffel/lib/io/directory_notation.e";
p[51]="/usr/local/opt/SmartEiffel/lib/io/filter.e";
p[26]="/usr/local/opt/SmartEiffel/lib/io/output_stream.e";
p[113]="/usr/local/opt/SmartEiffel/lib/io/path_name.e";
p[71]="/usr/local/opt/SmartEiffel/lib/io/filter_input_stream.e";
p[38]="/usr/local/opt/SmartEiffel/lib/io/terminal_output_stream.e";
p[104]="/usr/local/opt/SmartEiffel/lib/io/file_tools.e";
p[42]="/usr/local/opt/SmartEiffel/lib/io/terminal_input_stream.e";
p[41]="/usr/local/opt/SmartEiffel/lib/io/terminal_input_output_stream.e";
p[59]="/usr/local/opt/SmartEiffel/lib/io/filter_output_stream.e";
p[43]="/usr/local/opt/SmartEiffel/lib/io/input_stream.e";
p[27]="/usr/local/opt/SmartEiffel/lib/io/stream.e";
p[50]="/usr/local/opt/SmartEiffel/lib/io/terminal/file.e";
p[49]="/usr/local/opt/SmartEiffel/lib/io/terminal/text_file_read.e";
p[40]="/usr/local/opt/SmartEiffel/lib/io/terminal/std_input_output.e";
p[37]="/usr/local/opt/SmartEiffel/lib/io/terminal/std_error.e";
p[48]="/usr/local/opt/SmartEiffel/lib/io/terminal/std_input.e";
p[47]="/usr/local/opt/SmartEiffel/lib/io/terminal/std_output.e";
p[44]="/usr/local/opt/SmartEiffel/lib/io/low_level/input_stream_tools.e";
p[30]="/usr/local/opt/SmartEiffel/lib/io/low_level/output_stream_tools.e";
p[39]="/usr/local/opt/SmartEiffel/lib/io/low_level/redirection_tools.e";
p[105]="/usr/local/opt/SmartEiffel/lib/io/low_level/basic_directory.e";
p[115]="/usr/local/opt/SmartEiffel/lib/io/internal/unixish_path_name.e";
p[29]="/usr/local/opt/SmartEiffel/lib/io/internal/filterable.e";
p[112]="/usr/local/opt/SmartEiffel/lib/io/internal/path_joiner.e";
p[114]="/usr/local/opt/SmartEiffel/lib/io/path_name/posix_path_name.e";
p[111]="/usr/local/opt/SmartEiffel/lib/io/path_name/path_name_notation.e";
p[109]="/usr/local/opt/SmartEiffel/lib/io/path_name/macintosh_directory_notation.e";
p[117]="/usr/local/opt/SmartEiffel/lib/io/path_name/openvms_directory_notation.e";
p[120]="/usr/local/opt/SmartEiffel/lib/io/path_name/microsoft_path_name.e";
p[119]="/usr/local/opt/SmartEiffel/lib/io/path_name/windows_directory_notation.e";
p[110]="/usr/local/opt/SmartEiffel/lib/io/path_name/unix_directory_notation.e";
p[118]="/usr/local/opt/SmartEiffel/lib/io/path_name/amiga_directory_notation.e";
p[121]="/usr/local/opt/SmartEiffel/lib/io/path_name/cygwin_directory_notation.e";
p[107]="/usr/local/opt/SmartEiffel/lib/unicode/unicode_string_handler.e";
p[62]="/usr/local/opt/SmartEiffel/lib/iterator/iterator.e";
p[83]="/usr/local/opt/SmartEiffel/lib/iterator/internal/iterator_on_traversable.e";
p[81]="/usr/local/opt/SmartEiffel/lib/iterator/internal/iterator_on_unicode_string.e";
p[70]="/usr/local/opt/SmartEiffel/lib/iterator/internal/iterator_on_string.e";
p[84]="/usr/local/opt/SmartEiffel/lib/misc/mini_parser_buffer.e";
p[82]="/usr/local/opt/SmartEiffel/lib/sequencer/events_set.e";
p[60]="/usr/local/opt/SmartEiffel/lib/sequencer/event_descriptor.e";
p[72]="/usr/local/opt/SmartEiffel/lib/sequencer/events/can_read_data_from_stream.e";
p[98]="/usr/local/opt/SmartEiffel/lib/sequencer/events/network_connection_occurred.e";
p[61]="/usr/local/opt/SmartEiffel/lib/sequencer/events/can_write_data_to_stream.e";
p[28]="/usr/local/opt/SmartEiffel/lib/abilities/recyclable.e";
p[92]="/usr/local/opt/SmartEiffel/lib/abilities/disposable.e";
p[32]="/usr/local/opt/SmartEiffel/lib/abilities/traversable.e";
p[35]="/usr/local/opt/SmartEiffel/lib/abilities/hashable.e";
p[33]="/usr/local/opt/SmartEiffel/lib/abilities/storable.e";
p[34]="/usr/local/opt/SmartEiffel/lib/abilities/comparable.e";
p[12]="/usr/local/opt/SmartEiffel/lib/numeric/real_extended.e";
p[56]="/usr/local/opt/SmartEiffel/lib/numeric/real_general.e";
p[2]="/usr/local/opt/SmartEiffel/lib/numeric/integer_32.e";
p[57]="/usr/local/opt/SmartEiffel/lib/numeric/number.e";
p[4]="/usr/local/opt/SmartEiffel/lib/numeric/real_32.e";
p[1]="/usr/local/opt/SmartEiffel/lib/numeric/integer_8.e";
p[76]="/usr/local/opt/SmartEiffel/lib/numeric/mutable_big_integer.e";
p[11]="/usr/local/opt/SmartEiffel/lib/numeric/integer_64.e";
p[69]="/usr/local/opt/SmartEiffel/lib/numeric/number_tools.e";
p[54]="/usr/local/opt/SmartEiffel/lib/numeric/integer_general.e";
p[5]="/usr/local/opt/SmartEiffel/lib/numeric/real_64.e";
p[55]="/usr/local/opt/SmartEiffel/lib/numeric/numeric.e";
p[10]="/usr/local/opt/SmartEiffel/lib/numeric/integer_16.e";
p[77]="/usr/local/opt/SmartEiffel/lib/numeric/internal/fraction_with_big_integer_number.e";
p[74]="/usr/local/opt/SmartEiffel/lib/numeric/internal/integer_64_number.e";
p[75]="/usr/local/opt/SmartEiffel/lib/numeric/internal/integer_general_number.e";
p[78]="/usr/local/opt/SmartEiffel/lib/numeric/internal/fraction_general_number.e";
p[79]="/usr/local/opt/SmartEiffel/lib/numeric/internal/big_integer_number.e";
p[58]="/usr/local/opt/SmartEiffel/lib/string/unicode_string.e";
p[3]="/usr/local/opt/SmartEiffel/lib/string/character.e";
p[7]="/usr/local/opt/SmartEiffel/lib/string/string.e";
p[31]="/usr/local/opt/SmartEiffel/lib/string/low_level/string_handler.e";
p[108]="/usr/local/opt/SmartEiffel/lib/time/time_formatter.e";
p[90]="/usr/local/opt/SmartEiffel/lib/time/time.e";
p[86]="/usr/local/opt/SmartEiffel/lib/time/microsecond_time.e";
p[95]="/usr/local/opt/SmartEiffel/lib/net/access.e";
p[97]="/usr/local/opt/SmartEiffel/lib/net/socket_input_output_stream.e";
p[87]="/usr/local/opt/SmartEiffel/lib/net/low_level/socket_server.e";
p[103]="/usr/local/opt/SmartEiffel/lib/net/low_level/client_socket_input_output_stream.e";
p[96]="/usr/local/opt/SmartEiffel/lib/net/low_level/server_socket_input_output_stream.e";
p[88]="/usr/local/opt/SmartEiffel/lib/net/low_level/socket_plug_in.e";
p[89]="/usr/local/opt/SmartEiffel/lib/net/low_level/socket_handler.e";
p[91]="/usr/local/opt/SmartEiffel/lib/net/low_level/socket.e";
p[116]="/usr/local/opt/SmartEiffel/lib/exec/system.e";
se_prinT[49]=((void(*)(FILE*,void*))se_prinT49);
se_prinT[48]=((void(*)(FILE*,void*))se_prinT48);
se_prinT[47]=((void(*)(FILE*,void*))se_prinT47);
se_prinT[40]=((void(*)(FILE*,void*))se_prinT40);
se_prinT[25]=((void(*)(FILE*,void*))se_prinT25);
se_prinT[10]=((void(*)(FILE*,void*))se_prinT10);
se_prinT[9]=((void(*)(FILE*,void*))se_prinT9);
p[9]=p[52];
se_prinT[8]=((void(*)(FILE*,void*))se_prinT8);
se_prinT[7]=((void(*)(FILE*,void*))se_prinT7);
se_prinT[6]=((void(*)(FILE*,void*))se_prinT6);
se_prinT[3]=((void(*)(FILE*,void*))se_prinT3);
se_prinT[2]=((void(*)(FILE*,void*))se_prinT2);
se_prinT[1]=((void(*)(FILE*,void*))se_prinT1);
g[25]=(T7*)se_string("MEDIATHEQUE");
g[100]=(T7*)se_string("PROCEDURE");
g[94]=(T7*)se_string("MEMORY");
g[15]=(T7*)se_string("TUPLE 1");
g[16]=(T7*)se_string("TUPLE 2");
g[65]=(T7*)se_string("ROUTINE");
g[17]=(T7*)se_string("TUPLE 3");
g[18]=(T7*)se_string("TUPLE 4");
g[19]=(T7*)se_string("TUPLE 5");
g[20]=(T7*)se_string("TUPLE 6");
g[21]=(T7*)se_string("TUPLE 7");
g[22]=(T7*)se_string("TUPLE 8");
g[23]=(T7*)se_string("TUPLE 9");
g[14]=(T7*)se_string("TUPLE");
g[24]=(T7*)se_string("TUPLE 10");
g[8]=(T7*)se_string("POINTER");
g[99]=(T7*)se_string("REFERENCE");
g[64]=(T7*)se_string("FUNCTION");
g[6]=(T7*)se_string("BOOLEAN");
g[53]=(T7*)se_string("SAFE_EQUAL");
g[13]=(T7*)se_string("ANY");
g[101]=(T7*)se_string("WEAK_REFERENCE");
g[36]=(T7*)se_string("PLATFORM");
g[73]=(T7*)se_string("INTERNALS_HANDLER");
g[85]=(T7*)se_string("NATIVE_ARRAY_INTERNALS");
g[45]=(T7*)se_string("TYPED_INTERNALS");
g[67]=(T7*)se_string("NATIVE_ARRAY_COLLECTOR");
g[46]=(T7*)se_string("INTERNALS");
g[63]=(T7*)se_string("COLLECTION");
g[80]=(T7*)se_string("FAST_ARRAY");
g[66]=(T7*)se_string("ARRAY");
g[102]=(T7*)se_string("RING_ARRAY");
g[52]=(T7*)se_string("NATIVE_ARRAY");
g[93]=(T7*)se_string("RECYCLING_POOL");
g[68]=(T7*)se_string("ARRAYED_COLLECTION");
g[106]=(T7*)se_string("DIRECTORY_NOTATION");
g[51]=(T7*)se_string("FILTER");
g[26]=(T7*)se_string("OUTPUT_STREAM");
g[113]=(T7*)se_string("PATH_NAME");
g[71]=(T7*)se_string("FILTER_INPUT_STREAM");
g[38]=(T7*)se_string("TERMINAL_OUTPUT_STREAM");
g[104]=(T7*)se_string("FILE_TOOLS");
g[42]=(T7*)se_string("TERMINAL_INPUT_STREAM");
g[41]=(T7*)se_string("TERMINAL_INPUT_OUTPUT_STREAM");
g[59]=(T7*)se_string("FILTER_OUTPUT_STREAM");
g[43]=(T7*)se_string("INPUT_STREAM");
g[27]=(T7*)se_string("STREAM");
g[50]=(T7*)se_string("FILE");
g[49]=(T7*)se_string("TEXT_FILE_READ");
g[40]=(T7*)se_string("STD_INPUT_OUTPUT");
g[37]=(T7*)se_string("STD_ERROR");
g[48]=(T7*)se_string("STD_INPUT");
g[47]=(T7*)se_string("STD_OUTPUT");
g[44]=(T7*)se_string("INPUT_STREAM_TOOLS");
g[30]=(T7*)se_string("OUTPUT_STREAM_TOOLS");
g[39]=(T7*)se_string("REDIRECTION_TOOLS");
g[105]=(T7*)se_string("BASIC_DIRECTORY");
g[115]=(T7*)se_string("UNIXISH_PATH_NAME");
g[29]=(T7*)se_string("FILTERABLE");
g[112]=(T7*)se_string("PATH_JOINER");
g[114]=(T7*)se_string("POSIX_PATH_NAME");
g[111]=(T7*)se_string("PATH_NAME_NOTATION");
g[109]=(T7*)se_string("MACINTOSH_DIRECTORY_NOTATION");
g[117]=(T7*)se_string("OPENVMS_DIRECTORY_NOTATION");
g[120]=(T7*)se_string("MICROSOFT_PATH_NAME");
g[119]=(T7*)se_string("WINDOWS_DIRECTORY_NOTATION");
g[110]=(T7*)se_string("UNIX_DIRECTORY_NOTATION");
g[118]=(T7*)se_string("AMIGA_DIRECTORY_NOTATION");
g[121]=(T7*)se_string("CYGWIN_DIRECTORY_NOTATION");
g[107]=(T7*)se_string("UNICODE_STRING_HANDLER");
g[62]=(T7*)se_string("ITERATOR");
g[83]=(T7*)se_string("ITERATOR_ON_TRAVERSABLE");
g[81]=(T7*)se_string("ITERATOR_ON_UNICODE_STRING");
g[70]=(T7*)se_string("ITERATOR_ON_STRING");
g[84]=(T7*)se_string("MINI_PARSER_BUFFER");
g[82]=(T7*)se_string("EVENTS_SET");
g[60]=(T7*)se_string("EVENT_DESCRIPTOR");
g[72]=(T7*)se_string("CAN_READ_DATA_FROM_STREAM");
g[98]=(T7*)se_string("NETWORK_CONNECTION_OCCURRED");
g[61]=(T7*)se_string("CAN_WRITE_DATA_TO_STREAM");
g[28]=(T7*)se_string("RECYCLABLE");
g[92]=(T7*)se_string("DISPOSABLE");
g[32]=(T7*)se_string("TRAVERSABLE");
g[35]=(T7*)se_string("HASHABLE");
g[33]=(T7*)se_string("STORABLE");
g[34]=(T7*)se_string("COMPARABLE");
g[12]=(T7*)se_string("REAL_EXTENDED");
g[56]=(T7*)se_string("REAL_GENERAL");
g[2]=(T7*)se_string("INTEGER_32");
g[57]=(T7*)se_string("NUMBER");
g[4]=(T7*)se_string("REAL_32");
g[1]=(T7*)se_string("INTEGER_8");
g[76]=(T7*)se_string("MUTABLE_BIG_INTEGER");
g[11]=(T7*)se_string("INTEGER_64");
g[69]=(T7*)se_string("NUMBER_TOOLS");
g[54]=(T7*)se_string("INTEGER_GENERAL");
g[5]=(T7*)se_string("REAL_64");
g[55]=(T7*)se_string("NUMERIC");
g[10]=(T7*)se_string("INTEGER_16");
g[77]=(T7*)se_string("FRACTION_WITH_BIG_INTEGER_NUMBER");
g[74]=(T7*)se_string("INTEGER_64_NUMBER");
g[75]=(T7*)se_string("INTEGER_GENERAL_NUMBER");
g[78]=(T7*)se_string("FRACTION_GENERAL_NUMBER");
g[79]=(T7*)se_string("BIG_INTEGER_NUMBER");
g[58]=(T7*)se_string("UNICODE_STRING");
g[3]=(T7*)se_string("CHARACTER");
g[7]=(T7*)se_string("STRING");
g[31]=(T7*)se_string("STRING_HANDLER");
g[108]=(T7*)se_string("TIME_FORMATTER");
g[90]=(T7*)se_string("TIME");
g[86]=(T7*)se_string("MICROSECOND_TIME");
g[95]=(T7*)se_string("ACCESS");
g[97]=(T7*)se_string("SOCKET_INPUT_OUTPUT_STREAM");
g[87]=(T7*)se_string("SOCKET_SERVER");
g[103]=(T7*)se_string("CLIENT_SOCKET_INPUT_OUTPUT_STREAM");
g[96]=(T7*)se_string("SERVER_SOCKET_INPUT_OUTPUT_STREAM");
g[88]=(T7*)se_string("SOCKET_PLUG_IN");
g[89]=(T7*)se_string("SOCKET_HANDLER");
g[91]=(T7*)se_string("SOCKET");
g[116]=(T7*)se_string("SYSTEM");
g[9]=g[52];
t[49]=g[49];
t[48]=g[48];
t[47]=g[47];
t[40]=g[40];
t[25]=g[25];
t[10]=g[10];
t[9]=(T7*)se_string("NATIVE_ARRAY[CHARACTER]");
t[8]=g[8];
t[7]=g[7];
t[6]=g[6];
t[3]=g[3];
t[2]=g[2];
t[1]=g[1];
#ifdef SIGINT
signal(SIGINT,se_signal_handler);
#endif
#ifdef SIGTERM
signal(SIGTERM,se_signal_handler);
#endif
#ifdef SIGQUIT
signal(SIGQUIT,se_signal_handler);
#endif
#ifdef SIGILL
signal(SIGILL,se_signal_handler);
#endif
#ifdef SIGABRT
signal(SIGABRT,se_signal_handler);
#endif
#ifdef SIGFPE
signal(SIGFPE,se_signal_handler);
#endif
#ifdef SIGSEGV
signal(SIGSEGV,se_signal_handler);
#endif
#ifdef SIGBUS
signal(SIGBUS,se_signal_handler);
#endif
#ifdef SIGSYS
signal(SIGSYS,se_signal_handler);
#endif
#ifdef SIGTRAP
signal(SIGTRAP,se_signal_handler);
#endif
#ifdef SIGXCPU
signal(SIGXCPU,se_signal_handler);
#endif
#ifdef SIGXFSZ
signal(SIGXFSZ,se_signal_handler);
#endif
gc_is_off=0;
tmp0=((T0*)(new25()));
eiffel_root_object=((T25*)tmp0);
set_dump_stack_top((void*)0);/*unlink*/
}/*--*/

int main(int argc,char*argv[]){
/*[INTERNAL_C_LOCAL list*/
T0* tmp0;
/*INTERNAL_C_LOCAL list]*/
se_frame_descriptor root={"<system root>",1,0,"%R25%",1};
se_dump_stack ds;
stack_bottom=((void**)(void*)(&argc));
initialize_eiffel_runtime(argc,argv);
tmp0=((T0*)eiffel_root_object);
ds.fd=&root;
ds.current=((void*)(&tmp0));
ds.p=0x03200E04/*l14c2/mediatheque.e*/;
ds.caller=NULL;
ds.exception_origin=NULL;
ds.locals=NULL;
set_dump_stack_top(&ds);/*link*/
r25make(&ds,((T25*)tmp0));
handle(SE_HANDLE_NORMAL_EXIT, NULL);
set_dump_stack_top(NULL);/*unlink*/
exit(0);
return 0;
}/*--*/

#ifdef __cplusplus
}
#endif
